### ISSUE TITLE
v0.2.1 broke existing workflows - 'SingleHdf5ToZarr' object has no attribute 'decoders'

### ISSUE THREAD

**Issue by rabernat** [fsspec/kerchunk#382]
Here's an example that works with 0.2.0 but not with 0.2.1

```python
from kerchunk.hdf import SingleHdf5ToZarr
import fsspec
import json 
import s3fs

s3 = s3fs.S3FileSystem()
url = 's3://era5-pds/2023/01/data/precipitation_amount_1hour_Accumulation.nc'

fs2 = fsspec.filesystem('')

so = dict(mode='rb',  default_fill_cache=False, default_cache_type='first')

with s3.open(url, **so) as infile:
    h5chunks = SingleHdf5ToZarr(infile, url, inline_threshold=0)
    outf = "kerchunk.json"
    with fs2.open(outf, 'wb') as f:
        f.write(json.dumps(h5chunks.translate()).encode())
```

This produces the warning

```
/srv/conda/envs/notebook/lib/python3.11/site-packages/kerchunk/hdf.py:494: UserWarning: The following excepion was caught and quashed while traversing HDF5
'SingleHdf5ToZarr' object has no attribute 'decoders'
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.11/site-packages/kerchunk/hdf.py", line 262, in _translator
    filters = self._decode_filters(h5obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.11/site-packages/kerchunk/hdf.py", line 246, in _decode_filters
    f" not supported by kerchunk., supported filters are {self.decoders.keys()}"
                                                          ^^^^^^^^^^^^^
AttributeError: 'SingleHdf5ToZarr' object has no attribute 'decoders'

  warnings.warn(msg)
```

And the resulting `kerchunk.json` is missing the reference data.

**Comment by norlandrhagen** [comment]
Seconded, just hit the same error with latest.

**Comment by martindurant** [comment]
Please test with the linked PR. I can release a quick fix as soon as it it merged.
