### PR TITLE
Do not handle shuffle twice

### LINKED ISSUE #382: v0.2.1 broke existing workflows - 'SingleHdf5ToZarr' object has no attribute 'decoders'
Here's an example that works with 0.2.0 but not with 0.2.1

```python
from kerchunk.hdf import SingleHdf5ToZarr
import fsspec
import json 
import s3fs

s3 = s3fs.S3FileSystem()
url = 's3://era5-pds/2023/01/data/precipitation_amount_1hour_Accumulation.nc'

fs2 = fsspec.filesystem('')

so = dict(mode='rb',  default_fill_cache=False, default_cache_type='first')

with s3.open(url, **so) as infile:
    h5chunks = SingleHdf5ToZarr(infile, url, inline_threshold=0)
    outf = "kerchunk.json"
    with fs2.open(outf, 'wb') as f:
        f.write(json.dumps(h5chunks.translate()).encode())
```

This produces the warning

```
/srv/conda/envs/notebook/lib/python3.11/site-packages/kerchunk/hdf.py:494: UserWarning: The following excepion was caught and quashed while traversing HDF5
'SingleHdf5ToZarr' object has no attribute 'decoders'
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.11/site-packages/kerchunk/hdf.py", line 262, in _translator
    filters = self._decode_filters(h5obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.11/site-packages/kerchunk/hdf.py", line 246, in _decode_filters
    f" not supported by kerchunk., supported filters are {self.decoders.keys()}"
                                                          ^^^^^^^^^^^^^
AttributeError: 'SingleHdf5ToZarr' object has no attribute 'decoders'

  warnings.warn(msg)
```

And the resulting `kerchunk.json` is missing the reference data.

### PR DESCRIPTION
**Pull request by martindurant**
Fix #382

### CODE REVIEW

**Comment by rabernat** [comment]
We'd love to help add a test against #382. Any advice on where to start?

**Comment by martindurant** [comment]
> We'd love to help add a test against https://github.com/fsspec/kerchunk/issues/382

I ran against your file, of course.

For a test in CI, you could resurrect https://github.com/fsspec/kerchunk/pull/274, and build in some of these various compression/shuffle/encoding options. I don't really know how to make hdf files which would exercise all of the code paths in SingleHdf5ToZarr .

**Comment by martindurant** [comment]
Removing my stuff and simply using
```
    return tuple(tuple(ch) for ch in chunks)
```
on the last line would be much better, but there are two tests specifically passing float("nan") to check the current behaviour.

**Comment by martindurant** [comment]
But OK to merge and quick release here?

**Comment by rabernat** [comment]
Sure, we appreciate the quick fix! 🙏 

We'll think about how to address the testing question, which is needed in order to guard against the same problem happening in the future.
